# Service Account Key authentication method
# See Authentication methods below for more config options
data_source bigquery_soda:
  type: bigquery
  account_info_json_path: ${GOOGLE_APPLICATION_CREDENTIALS}
  auth_scopes:
  - https://www.googleapis.com/auth/bigquery
  - https://www.googleapis.com/auth/cloud-platform
  - https://www.googleapis.com/auth/drive
  project_id: ${PROJECT_ID}
  dataset: ${DATASET_ID}
